[package]
name = "guest"
version = "0.13.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.13"

[dependencies]
json = "0.12"
serde_json = "1.0.93"
risc0-zkvm = { version = "0.13", default_features = false, features = [ "std" ] }
