[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.11"

[dependencies]
homebase-core = { path = "../../core" }
risc0-zkvm-guest = "0.11"
json = "0.12"
fhir-rs = { path = "../../fhir/fhir-rs" }