[package]
name = "medical-core"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "0.14.0", default-features = false, features = [ "std" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
