[package]
name = "homebase-core"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkp = { version = "0.11", default-features = false }
serde = "1.0"
json = "0.12"
serde_json = "1.0.93"
chrono = { version = "0.4.23", features = ["serde"] }
fhir = "0.0.6"