[package]
name = "homebase-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.93"
risc0-zkvm = { version = "0.12", default-features = false, features = [ "std" ] }
methods = { path = "../methods" }
