[package]
name = "server"
version = "0.1.0"
edition = "2021" 

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
medical= { path = "../medical" }
authenticate = { path = "../authenticate" }
