[package]
name = "search_json"
version = "0.12.0"
edition = "2021"

[workspace]

[dependencies]
json = "0.12"
authenticate-broker = { path = "../../authenticate" }
risc0-zkvm = { version = "0.14.0", default-features = false }
